---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"
vars:
  region: "%{hiera('region')}"

  user_name: "test-%{hiera('deployment_identifier')}"
  user_public_gpg_key_path: "%{hiera('public_gpg_key_path')}"
